language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2
before_install:
  - sudo apt-get update; sudo apt-get install libglfw3 -y
  - gem install bundler
  - gem update --system
script:
  - bundle exec rake test